# Generated by Django 3.2.6 on 2021-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='product_image'),
        ),
    ]
