# Generated by Django 3.2.6 on 2021-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210828_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('dollar', 'US Dollars'), ('rupees', 'INR Rupees ')], default='rupees', max_length=10),
        ),
    ]
